import { createHash } from 'node:crypto';
// eslint-disable-next-line @stylistic/object-curly-newline -- Keep formatter-compatible Node imports compact.
import { readFile, writeFile } from 'node:fs/promises';

const CASE_FOLDING_VERSION = '17.0.0';
const COMMON_RECORD_COUNT = 1481;
const FULL_RECORD_COUNT = 104;
const HEXADECIMAL_RADIX = 16;
const INPUT_ARGUMENT_INDEX = 2;
const OUTPUT_PATH = 'src/unicode-case-folding.ts';
const SOURCE_SHA256 = 'ff8d8fefbf123574205085d6714c36149eb946d717a0c585c27f0f4ef58c4183';
const SOURCE_URL = `https://www.unicode.org/Public/${CASE_FOLDING_VERSION}/ucd/CaseFolding.txt`;
const VERSION_HEADER = `# CaseFolding-${CASE_FOLDING_VERSION}.txt`;
const RECORD_PATTERN = /^(?<codePoint>[\dA-F]+); (?<status>[CF]); (?<mapping>[\dA-F ]+);/u;

const sourcePath = process.argv[INPUT_ARGUMENT_INDEX];
if (sourcePath === undefined) {
  throw new Error(
    `Usage: pnpm exec jiti scripts/generate-unicode-case-folding.ts <CaseFolding.txt>\nSource: ${SOURCE_URL}`
  );
}

const source = await readFile(sourcePath, 'utf-8');
if (!source.startsWith(VERSION_HEADER)) {
  throw new Error(`Expected ${VERSION_HEADER} from ${SOURCE_URL}.`);
}
const sourceSha256 = createHash('sha256').update(source).digest('hex');
if (sourceSha256 !== SOURCE_SHA256) {
  throw new Error(
    `Expected SHA-256 ${SOURCE_SHA256} for ${SOURCE_URL}, received ${sourceSha256}.`
  );
}

const mappings = new Map<number, string>();
let commonRecordCount = 0;
let fullRecordCount = 0;
for (const line of source.split('\n')) {
  const match = RECORD_PATTERN.exec(line);
  const codePointSource = match?.groups?.['codePoint'];
  const mappingSource = match?.groups?.['mapping'];
  const status = match?.groups?.['status'];
  if (
    codePointSource === undefined
    || mappingSource === undefined
    || status === undefined
  ) {
    continue;
  }

  const codePoint = Number.parseInt(codePointSource, HEXADECIMAL_RADIX);
  const mapping = mappingSource
    .trim()
    .split(' ')
    .map((value) => String.fromCodePoint(Number.parseInt(value, HEXADECIMAL_RADIX)))
    .join('');
  if (mappings.has(codePoint)) {
    throw new Error(`Duplicate full case-fold mapping for U+${codePointSource}.`);
  }
  mappings.set(codePoint, mapping);
  if (status === 'C') {
    commonRecordCount += 1;
  } else {
    fullRecordCount += 1;
  }
}

if (
  commonRecordCount !== COMMON_RECORD_COUNT
  || fullRecordCount !== FULL_RECORD_COUNT
) {
  throw new Error(
    `Expected ${String(COMMON_RECORD_COUNT)} common and ${String(FULL_RECORD_COUNT)} full records, received ${
      String(commonRecordCount)
    } and ${String(fullRecordCount)}.`
  );
}

const entries = Array.from(
  mappings,
  ([codePoint, mapping], index) => {
    const comma = index === mappings.size - 1 ? '' : ',';
    return `  [0x${codePoint.toString(HEXADECIMAL_RADIX).toUpperCase()}, ${formatStringLiteral(mapping)}]${comma}`;
  }
).join('\n');
const output = `/*
 * Generated by scripts/generate-unicode-case-folding.ts from:
 * ${SOURCE_URL}
 * Unicode CaseFolding-${CASE_FOLDING_VERSION}.txt, statuses C and F (default full case folding).
 * Source SHA-256: ${SOURCE_SHA256}
 * ${String(mappings.size)} generated mappings: ${String(COMMON_RECORD_COUNT)} common and ${
  String(FULL_RECORD_COUNT)
} full.
 *
 * UNICODE LICENSE V3
 *
 * COPYRIGHT AND PERMISSION NOTICE
 *
 * Copyright © 1991-2026 Unicode, Inc.
 *
 * NOTICE TO USER: Carefully read the following legal agreement. BY
 * DOWNLOADING, INSTALLING, COPYING OR OTHERWISE USING DATA FILES, AND/OR
 * SOFTWARE, YOU UNEQUIVOCALLY ACCEPT, AND AGREE TO BE BOUND BY, ALL OF THE
 * TERMS AND CONDITIONS OF THIS AGREEMENT. IF YOU DO NOT AGREE, DO NOT
 * DOWNLOAD, INSTALL, COPY, DISTRIBUTE OR USE THE DATA FILES OR SOFTWARE.
 *
 * Permission is hereby granted, free of charge, to any person obtaining a
 * copy of data files and any associated documentation (the "Data Files") or
 * software and any associated documentation (the "Software") to deal in the
 * Data Files or Software without restriction, including without limitation
 * the rights to use, copy, modify, merge, publish, distribute, and/or sell
 * copies of the Data Files or Software, and to permit persons to whom the
 * Data Files or Software are furnished to do so, provided that either (a)
 * this copyright and permission notice appear with all copies of the Data
 * Files or Software, or (b) this copyright and permission notice appear in
 * associated Documentation.
 *
 * THE DATA FILES AND SOFTWARE ARE PROVIDED "AS IS", WITHOUT WARRANTY OF ANY
 * KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
 * MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT OF
 * THIRD PARTY RIGHTS.
 *
 * IN NO EVENT SHALL THE COPYRIGHT HOLDER OR HOLDERS INCLUDED IN THIS NOTICE
 * BE LIABLE FOR ANY CLAIM, OR ANY SPECIAL INDIRECT OR CONSEQUENTIAL DAMAGES,
 * OR ANY DAMAGES WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS,
 * WHETHER IN AN ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION,
 * ARISING OUT OF OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THE DATA
 * FILES OR SOFTWARE.
 *
 * Except as contained in this notice, the name of a copyright holder shall
 * not be used in advertising or otherwise to promote the sale, use or other
 * dealings in these Data Files or Software without prior written
 * authorization of the copyright holder.
 *
 * License source: https://www.unicode.org/license.txt
 */

/* eslint-disable no-magic-numbers, perfectionist/sort-maps, unicorn/numeric-separators-style -- Generated code points preserve Unicode source order and notation. */
const CASE_FOLDING_MAP: ReadonlyMap<number, string> = new Map([
${entries}
]);
/* eslint-enable no-magic-numbers, perfectionist/sort-maps, unicorn/numeric-separators-style -- Re-enable outside generated data. */

export function foldUnicodeCase(value: string): string {
  let folded = '';
  for (const character of value) {
    const codePoint = character.codePointAt(0);
    folded += codePoint === undefined
      ? character
      : CASE_FOLDING_MAP.get(codePoint) ?? character;
  }
  return folded;
}
`;

await writeFile(OUTPUT_PATH, output);

function formatStringLiteral(value: string): string {
  const jsonString = JSON.stringify(value);
  return `'${jsonString.slice(1, -1).replaceAll('\'', String.raw`\'`)}'`;
}
